export const typingCSV = `
theme,level,text
"Saluti","A1","Ciao! Come stai? Io sto bene, grazie. E tu?"
"Numeri","A1","Uno, due, tre, quattro, cinque. Questi sono i primi cinque numeri in italiano."
"Colori","A2","Il rosso è un colore caldo. Il blu è un colore freddo. Il verde è il colore della natura."
"Famiglia","A2","La mia famiglia è composta da: padre, madre, fratello e sorella."
"Cibo","B1","La pasta, la pizza e il gelato sono cibi italiani molto famosi in tutto il mondo."
"Giorni della settimana","A1","Lunedì, martedì, mercoledì, giovedì, venerdì, sabato, domenica."
"Verbo essere","B1","Io sono, tu sei, lui/lei è, noi siamo, voi siete, loro sono. Questo è il verbo essere."
"Stagioni","A2","In Italia ci sono quattro stagioni: primavera, estate, autunno e inverno."
"Trasporti","B1","In città puoi spostarti in autobus, in metro, in taxi o in bicicletta."
"Saluti formali","B2","Buongiorno, signore. Come sta? Arrivederci e buona giornata!"
"Saluti","A1","Buonasera! Come va? Spero tu abbia passato una buona giornata."
"Saluti","A1","Mi chiamo Marco. E tu come ti chiami?"
"Numeri","A1","Sei, sette, otto, nove, dieci. Ecco i numeri da sei a dieci."
"Numeri","A1","Il numero zero è l'inizio di tutti i numeri."
"Colori","A2","Il giallo è il colore del sole. L'arancione è un colore vivace e caldo."
"Colori","A2","Il bianco è associato alla purezza, mentre il nero è spesso legato al mistero."
"Famiglia","A2","Mio nonno è un uomo gentile e saggio. Mia nonna è una donna affettuosa."
"Famiglia","A2","Ho due cugini che vivono in città e una zia che abita in campagna."
"Cibo","B1","Il cappuccino è una bevanda italiana preparata con espresso e latte schiumato."
"Cibo","B1","Il tiramisù è un dessert tipico italiano a base di mascarpone e caffè."
"Giorni della settimana","A1","Oggi è mercoledì, quindi domani sarà giovedì."
"Giorni della settimana","A1","Il weekend è composto da sabato e domenica."
"Verbo essere","B1","Lui è uno studente e lei è una insegnante. Noi siamo amici."
"Verbo essere","B1","Voi siete pronti per partire? Loro sono sempre puntuali."
"Stagioni","A2","La primavera porta con sé fiori e temperature più miti."
"Stagioni","A2","In inverno, le giornate sono più corte e le temperature più basse."
"Trasporti","B1","Il treno è un mezzo di trasporto veloce per viaggiare tra città."
"Trasporti","B1","La bicicletta è un mezzo ecologico e salutare per spostarsi in città."
"Saluti formali","B2","Egregio signore, la contatto per confermare l'appuntamento di domani."
"Saluti formali","B2","Cordiali saluti, e le auguro una serena giornata."
"Saluti","B1","È stato un piacere incontrarti oggi. Spero di vederti presto di nuovo."
"Saluti","B2","Mi permetta di presentarmi. Sono Luca e lavoro nel settore della tecnologia."
"Numeri","B1","I numeri romani sono usati per indicare le date importanti, come i secoli."
"Numeri","B2","Le statistiche dimostrano che il numero di turisti è aumentato del 20% negli ultimi anni."
"Colori","B1","Il blu navy è una tonalità di blu molto profonda, spesso utilizzata in ambito professionale."
"Colori","B2","Il verde smeraldo è considerato un colore regale e viene spesso utilizzato nella moda di alta classe."
"Famiglia","B1","Le dinamiche familiari possono essere complesse, specialmente quando ci sono molte generazioni coinvolte."
"Famiglia","B2","La struttura familiare tradizionale sta evolvendo, con un numero crescente di famiglie non convenzionali."
"Cibo","B1","La cucina italiana offre una vasta gamma di piatti regionali, ognuno con ingredienti e preparazioni unici."
"Cibo","B2","La gastronomia italiana è famosa per le sue ricette ricche e per l'uso di ingredienti freschi e di alta qualità."
"Giorni della settimana","B1","Il lunedì è spesso considerato un giorno di ripresa dopo il weekend, con una ripresa della routine quotidiana."
"Giorni della settimana","B2","La differenza tra i giorni feriali e il weekend può influenzare il nostro stato d'animo e la nostra produttività."
"Verbo essere","B1","Il verbo 'essere' è essenziale in italiano per costruire frasi al presente e descrivere stati e identità."
"Verbo essere","B2","Comprendere l'uso del verbo 'essere' in tutte le sue forme e tempi è fondamentale per una comunicazione efficace."
"Stagioni","B1","Ogni stagione ha il suo fascino: la primavera con i suoi fiori, l'estate con il sole, l'autunno con le foglie e l'inverno con la neve."
"Stagioni","B2","Le stagioni influenzano non solo il clima, ma anche la nostra vita quotidiana e le tradizioni culturali."
"Trasporti","B1","Il trasporto pubblico è un'alternativa ecologica all'uso dell'auto privata e contribuisce a ridurre l'inquinamento."
"Trasporti","B2","Le città moderne stanno investendo in infrastrutture per il trasporto sostenibile, come le reti di piste ciclabili e i mezzi elettrici."
"Saluti formali","B1","Gentile signora Rossi, la ringrazio per la sua disponibilità e attendo una sua risposta al più presto."
"Saluti formali","B2","Le scrivo per esprimere il mio sincero apprezzamento per il suo lavoro e per il supporto che ci ha fornito durante il progetto."
"Stagioni","B1","Durante l'estate, le giornate sono più lunghe e c'è più tempo per attività all'aperto."
"Stagioni","B1","Le vacanze estive sono l'occasione perfetta per visitare luoghi nuovi e rilassarsi con la famiglia."
"Stagioni","B2","L'estate in Italia è famosa per le sue splendide coste e le celebri località balneari come Amalfi e Cinque Terre."
"Stagioni","B2","Durante le vacanze estive, molti italiani partecipano a festival locali e sagre gastronomiche per celebrare le tradizioni."
"Cibo","B1","Durante le vacanze estive, è comune gustare piatti freschi come insalate, frutta e gelati rinfrescanti."
"Cibo","B1","Le grigliate estive, con carne e verdure, sono un passatempo popolare per le famiglie italiane durante i mesi caldi."
"Cibo","B2","Il gelato artigianale è una specialità italiana molto amata durante le calde giornate estive, con una vasta gamma di gusti."
"Cibo","B2","In estate, la cucina italiana si arricchisce di piatti freschi e leggeri, come la caprese e le bruschette."
"Trasporti","B1","Durante l'estate, il traffico verso le località turistiche può aumentare, quindi è utile pianificare in anticipo il viaggio."
"Trasporti","B1","Molti turisti preferiscono noleggiare biciclette o scooter per esplorare le città e le località costiere durante le vacanze estive."
"Trasporti","B2","Le compagnie di trasporti offrono spesso sconti speciali per i turisti durante la stagione estiva per incentivare i viaggi."
"Trasporti","B2","In estate, le stazioni ferroviarie e gli aeroporti possono essere molto affollati a causa dell'aumento dei viaggiatori in vacanza."
"Saluti","B1","Buone vacanze! Spero che tu possa goderti il sole e il relax che tanto meriti."
"Saluti","B1","Spero che tu abbia trascorso delle fantastiche vacanze estive e che tu sia tornato ricaricato e pronto per la nuova stagione."
"Saluti","B2","Ti auguro un'estate splendida e rilassante, ricca di esperienze indimenticabili e momenti felici con le persone che ami."
"Saluti","B2","Che la tua estate sia piena di avventure emozionanti e di momenti di tranquillità, lontano dallo stress quotidiano."
`;
