// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
// eslint-disable-next-line no-restricted-globals
const ignored = self.__WB_MANIFEST; // This line references __WB_MANIFEST

// You can add custom caching strategies for other routes or assets here.
// For example, to cache API calls:
/*
self.addEventListener('fetch', (event) => {
  if (event.request.url.includes('/api/')) {
    event.respondWith(
      caches.open('api-cache').then(async (cache) => {
        try {
          const response = await fetch(event.request);
          cache.put(event.request, response.clone());
          return response;
        } catch (error) {
          return cache.match(event.request);
        }
      })
    );
  }
});
*/

// Any other custom service worker logic can go here.
